title: the Society of Young Network Scientists (SYNS)
logo: /assets/img/logo.jpg
description: a society for the development of early-career network scientists
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
